import { Typography, Box } from '@mui/material';
import Link from 'next/link';
import LegalDocLayout from '@/components/legal/LegalDocLayout';
import {
  LegalSection,
  LegalNotice,
  LegalTOC,
  LegalContactGrid,
} from '@/components/legal/LegalSection';

export default function UrineTermsPage() {
  return (
    <LegalDocLayout
      productName="24H Urine Analysis"
      title="Terms of Service"
      version="1.0"
      lastUpdated="March 15, 2026"
      effectiveDate="March 15, 2026"
      intro=""
    >
      <LegalNotice warning>
        <Typography variant="body2">
          <strong>Important Notice:</strong> These terms govern your use of 24H Urine Analysis. By using the app, you agree to these terms. Please read them carefully. 24H Urine Analysis is developed and operated by Big Freight Life LLC.
        </Typography>
      </LegalNotice>

      <LegalTOC
        items={[
          { id: 'acceptance', label: 'Acceptance of Terms' },
          { id: 'educational-purpose', label: 'Educational Purpose Only \u2014 Not Medical Advice' },
          { id: 'user-responsibilities', label: 'User Responsibilities' },
          { id: 'ai-content', label: 'AI-Generated Content Disclaimer' },
          { id: 'privacy-data', label: 'Privacy and Data Handling' },
          { id: 'purchases', label: 'In-App Purchases and Subscriptions' },
          { id: 'cloud-storage', label: 'Cloud Document Storage' },
          { id: 'intellectual-property', label: 'Intellectual Property' },
          { id: 'limitation-liability', label: 'Limitation of Liability' },
          { id: 'indemnification', label: 'Indemnification' },
          { id: 'termination', label: 'Termination and Account Deletion' },
          { id: 'governing-law', label: 'Governing Law' },
          { id: 'changes', label: 'Changes to These Terms' },
          { id: 'contact', label: 'Contact Information' },
        ]}
      />

      {/* 1. Acceptance of Terms */}
      <LegalSection id="acceptance" title="1. Acceptance of Terms">
        <Typography variant="body1">
          By accessing or using the App, you confirm that you are at least 13 years of age and agree to comply with and be bound by these Terms. If you do not agree to these Terms, you must not use the App.
        </Typography>
      </LegalSection>

      {/* 2. Educational Purpose Only */}
      <LegalSection id="educational-purpose" title="2. Educational Purpose Only &mdash; Not Medical Advice">
        <LegalNotice warning>
          <Typography variant="body2">
            <strong>The App is designed for educational and informational purposes only.</strong> It is NOT a medical device and does NOT provide medical advice, diagnosis, or treatment.
          </Typography>
        </LegalNotice>
        <Typography variant="body1">
          All health insights, interpretations, risk assessments, and recommendations generated by the App are for general educational purposes and should never be used as a substitute for professional medical judgment.
        </Typography>
        <Typography variant="body1">
          Always consult a qualified healthcare provider before making any medical decisions. Do not disregard professional medical advice or delay seeking it because of information provided by this App. In case of a medical emergency, contact your local emergency services immediately.
        </Typography>
      </LegalSection>

      {/* 3. User Responsibilities */}
      <LegalSection id="user-responsibilities" title="3. User Responsibilities">
        <Typography variant="body1">
          As a user of the App, you agree to:
        </Typography>
        <Box component="ul">
          <li><Typography variant="body1">Provide accurate information when using the App.</Typography></li>
          <li><Typography variant="body1">Use the App only for its intended educational purpose.</Typography></li>
          <li><Typography variant="body1">Not rely on the App as a substitute for professional medical advice.</Typography></li>
          <li><Typography variant="body1">Keep your account credentials secure and not share them with others.</Typography></li>
          <li><Typography variant="body1">Not attempt to reverse engineer, decompile, or disassemble the App.</Typography></li>
          <li><Typography variant="body1">Not use the App for any unlawful or unauthorized purpose.</Typography></li>
          <li><Typography variant="body1">Comply with all applicable laws and regulations.</Typography></li>
        </Box>
      </LegalSection>

      {/* 4. AI-Generated Content Disclaimer */}
      <LegalSection id="ai-content" title="4. AI-Generated Content Disclaimer">
        <Typography variant="body1">
          The App uses artificial intelligence (Google Gemini via Vertex AI) to analyze lab report data and generate health insights. You acknowledge and agree that:
        </Typography>
        <Box component="ul">
          <li><Typography variant="body1">AI-generated content may contain errors, inaccuracies, or omissions.</Typography></li>
          <li><Typography variant="body1">AI interpretations are not reviewed by medical professionals before being displayed.</Typography></li>
          <li><Typography variant="body1">The accuracy of results depends on the quality and legibility of your uploaded lab reports.</Typography></li>
          <li><Typography variant="body1">AI models may produce different interpretations over time as they are updated.</Typography></li>
          <li><Typography variant="body1">The App does not guarantee the accuracy, completeness, or reliability of any AI-generated content.</Typography></li>
        </Box>
      </LegalSection>

      {/* 5. Privacy and Data Handling */}
      <LegalSection id="privacy-data" title="5. Privacy and Data Handling">
        <Typography variant="body1">
          Your privacy is important to us. Our collection, use, and protection of your personal information is governed by our{' '}
          <Link href="/legal/24h-urine-privacy">Privacy Policy</Link>, which is incorporated into these Terms by reference. By using the App, you consent to the data practices described in the Privacy Policy.
        </Typography>
        <Typography variant="body1">Key points include:</Typography>
        <Box component="ul">
          <li><Typography variant="body1">Lab report text is sent to Google Vertex AI for analysis. No images are transmitted.</Typography></li>
          <li><Typography variant="body1">Personal identifiable information (PII) is redacted before any data leaves your device.</Typography></li>
          <li><Typography variant="body1">Data is stored locally on your device and synced to Convex servers for cross-device access.</Typography></li>
          <li><Typography variant="body1">You control data retention periods through the App&apos;s privacy settings.</Typography></li>
          <li><Typography variant="body1">You can delete your account and all associated data at any time.</Typography></li>
        </Box>
      </LegalSection>

      {/* 6. In-App Purchases and Subscriptions */}
      <LegalSection id="purchases" title="6. In-App Purchases and Subscriptions">
        <Typography variant="body1">
          The App offers in-app purchases and subscriptions for additional analysis credits:
        </Typography>
        <Box component="ul">
          <li><Typography variant="body1">New users receive 1 free analysis credit upon account creation.</Typography></li>
          <li><Typography variant="body1">Additional analysis credits can be purchased: Single Analysis (1 credit) or 3-Pack (3 credits).</Typography></li>
          <li><Typography variant="body1">Monthly and Annual subscriptions provide unlimited analyses during the active subscription period.</Typography></li>
          <li><Typography variant="body1">The 24-Hour Pass grants unlimited analyses for 24 hours from the time of purchase and does not auto-renew.</Typography></li>
          <li><Typography variant="body1">All purchases are processed through the Apple App Store and are subject to Apple&apos;s terms and conditions.</Typography></li>
          <li><Typography variant="body1">Refunds are handled by Apple according to their refund policy.</Typography></li>
          <li><Typography variant="body1">Prices are displayed in your local currency and may vary by region.</Typography></li>
        </Box>
      </LegalSection>

      {/* 7. Cloud Document Storage */}
      <LegalSection id="cloud-storage" title="7. Cloud Document Storage">
        <Typography variant="body1">
          The App offers optional encrypted cloud storage for scanned lab documents:
        </Typography>
        <Box component="ul">
          <li><Typography variant="body1">Documents are encrypted on your device before upload using AES-256-GCM encryption.</Typography></li>
          <li><Typography variant="body1">Encryption keys are stored solely on your device and are not accessible to us.</Typography></li>
          <li><Typography variant="body1">You may opt in or out of cloud storage at any time through the App&apos;s settings.</Typography></li>
          <li><Typography variant="body1">Stored documents are retained until you delete them or delete your account.</Typography></li>
          <li><Typography variant="body1">We cannot access, read, or recover the contents of your encrypted documents.</Typography></li>
          <li><Typography variant="body1">Cloud storage availability depends on an active internet connection and valid account.</Typography></li>
        </Box>
      </LegalSection>

      {/* 8. Intellectual Property */}
      <LegalSection id="intellectual-property" title="8. Intellectual Property">
        <Typography variant="body1">
          The App and its original content, features, and functionality are owned by the developer and are protected by copyright, trademark, and other intellectual property laws. You are granted a limited, non-exclusive, non-transferable license to use the App for personal, non-commercial purposes in accordance with these Terms.
        </Typography>
      </LegalSection>

      {/* 9. Limitation of Liability */}
      <LegalSection id="limitation-liability" title="9. Limitation of Liability">
        <Typography variant="body1">
          <strong>TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE DEVELOPER SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT LIMITED TO LOSS OF PROFITS, DATA, OR HEALTH OUTCOMES, ARISING OUT OF OR IN CONNECTION WITH YOUR USE OF THE APP.</strong>
        </Typography>
        <Typography variant="body1">
          The App is provided &quot;as is&quot; and &quot;as available&quot; without warranties of any kind, whether express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, and non-infringement.
        </Typography>
        <Typography variant="body1">
          In no event shall the developer&apos;s total liability exceed the amount you paid for the App or its services in the twelve (12) months preceding the claim.
        </Typography>
      </LegalSection>

      {/* 10. Indemnification */}
      <LegalSection id="indemnification" title="10. Indemnification">
        <Typography variant="body1">
          You agree to indemnify, defend, and hold harmless the developer and its affiliates from and against any claims, liabilities, damages, losses, and expenses arising out of or in any way connected with your use of the App, your violation of these Terms, or your violation of any rights of a third party.
        </Typography>
      </LegalSection>

      {/* 11. Termination and Account Deletion */}
      <LegalSection id="termination" title="11. Termination and Account Deletion">
        <Typography variant="body1">
          You may stop using the App at any time. You can delete your account and all associated data through the App&apos;s Settings. We reserve the right to suspend or terminate your access to the App at our sole discretion, without notice, for conduct that we believe violates these Terms or is harmful to other users, us, or third parties.
        </Typography>
      </LegalSection>

      {/* 12. Governing Law */}
      <LegalSection id="governing-law" title="12. Governing Law">
        <Typography variant="body1">
          These Terms shall be governed by and construed in accordance with the laws of the United States, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be resolved in the appropriate courts of the applicable jurisdiction.
        </Typography>
      </LegalSection>

      {/* 13. Changes to These Terms */}
      <LegalSection id="changes" title="13. Changes to These Terms">
        <Typography variant="body1">
          We reserve the right to modify or replace these Terms at any time. If a revision is material, we will provide notice within the App. Your continued use of the App after any changes constitutes your acceptance of the new Terms.
        </Typography>
      </LegalSection>

      {/* 14. Contact Information */}
      <LegalSection id="contact" title="14. Contact Information">
        <LegalContactGrid
          items={[
            {
              label: 'Privacy Inquiries',
              content: (
                <a href="mailto:privacy@24hurineanalysis.com">privacy@24hurineanalysis.com</a>
              ),
            },
            {
              label: 'General Support',
              content: <a href="mailto:privacy@bflux.co">privacy@bflux.co</a>,
            },
            {
              label: 'Mailing Address',
              content: (
                <>
                  Big Freight Life LLC
                  <br />
                  1351 N Buckner Blvd #180397
                  <br />
                  Dallas, TX 75218, USA
                </>
              ),
            },
          ]}
        />
      </LegalSection>
    </LegalDocLayout>
  );
}
